name: Release
on:
  push:
    branches: [main]
permissions:
  contents: read # for checkout
jobs:
  release:
    # prevents this action from running on forks
    if: github.repository == 'binhtran432k/story-mapping-generator'
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Cache npm
        uses: actions/cache@v4
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node
          restore-keys: |
            ${{ runner.os }}-node
      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
